### ISSUE TITLE
Död kod?

### ISSUE THREAD

**Issue by grebdevs** [MrAkergren/CompSec_EDA263#1]
Rad 95-100 i skrivande stund senaste commiten, 949c316d78451b63d51efa085f732823dda93fe8, verkar det som att return-satsen utesluter att pwage inkrementeras. ~~Antar att enklaste lösningen är att lägga return-satsen efter inkrementeringen.~~ Ser nu att inkrementeringen borde ske ungefär vid rad 82, direkt efter att man har en konstaterat lyckad inloggning. Har inte testat själv, bara kikade på koden. :)

```
95              return(-1);
96              
97              if (++passwddata->pwage > 10) {
98                  //Just a reminder, no need to exit or quit.
99                  printf("Your password is old, you should change it!\n");
100             }
```

Fint i övrigt med kommentarer osv!

**Comment by grebdevs** [comment]
Utöver detta så kanske inte det borde vara return(-1) alls på rad 95, eftersom man kommer dit endast vid en lyckad SETUID. Det kanske är mer korrekt att returnera 0 vid en lyckad körning, eller att breaka ut till nollan sist i main-funktionen?

**Comment by MrAkergren** [comment]
closed with commit 272ee2faa6ce82709414a072ffc9a337b47b4faa
