### ISSUE TITLE
Lägga till ett par #defines

### ISSUE THREAD

**Issue by grebdevs** [MrAkergren/CompSec_EDA263#2]
Detaljer, jag vet, men man skulle kunna lägga till ett par defines för att "snygga till" lite.

Radnummer refererar till 949c316d78451b63d51efa085f732823dda93fe8.
- L77: `if(passwddata->pwfailed >= 3){` Ersätta 3 med `#define MAX_LOGIN_ATTEMPTS 3`
- L83: `if(setuid(passwddata->uid) == 0) {` Ersätta 0 med t.ex. `#define SETUID_SUCCESS 0`
- L97: `if (++passwddata->pwage > 10) {` Ersätta 10 med något i stil med  `#define OLD_PW 10`

**Comment by MrAkergren** [comment]
closed with commit ed5dbc2
